### ISSUE TITLE
Performance issues when having >1000 markers.

### ISSUE THREAD

**Issue by oskaryil** [venits/react-native-map-clustering#1]
Great job on this one I must say although I found that it couldn't handle >1000 markers without performance issues. Is this an issue with react-native-maps in general or with your mods?

**Comment by venits** [comment]
Hi, thanks for noticing this. I forgot to mention that this solution can't handle thousands of markers well but I know a way to improve it. I will work on algorithm and maybe in few days I will post better version :)

**Comment by venits** [comment]
Hi, sorry for not responding for so long. 

Actually I have a solution but it is not unique and it depends on your markers position. 

Basically all we have to do to improve performance is to divide markers into smaller groups for example if you have markers all over the world then you create arrays of markers for each country. 

It will simplify calculations for algorithm but it will lead to some issues but overall user should not notice that.

I say this solution is not unique because for example app can have markers only in one city, and then we have to create arrays of markers for parts of the city.

If you are in need of high performance for over 1000 markers then let me know I will help you to write with that :)

It's not much work to do but we will have to divide your map depending on your markers.

**Comment by sberryman** [comment]
@venits have you looked at [supercluster](https://github.com/mapbox/supercluster) at all?

**Comment by venits** [comment]
Nope but I will for sure :) Maybe I will find something useful for my module.

**Comment by bcalik** [comment]
Whats the point of clustering if you can't get any performance benefit.

You should be using supercluster library.

**Comment by oskaryil** [comment]
Hoping that this will get implemented (fingers crossed)

**Comment by venits** [comment]
**Good news! ;)**
Supercluster is here.

I rewrote whole algorithm so now it is using Supercluster module.

It is much faster now but still needs testing. 
I hope you will help me with finding all errors ;)
