### ISSUE TITLE
Unhandled JS Exception: Tried to register two views with the same name AIRMap

### ISSUE THREAD

**Issue by jetonk** [venits/react-native-map-clustering#108]
I installed this module and when I try to render the Map with the Markers I see this Error:

![IMG_1482](https://user-images.githubusercontent.com/10130015/65690398-3fed0380-e06f-11e9-9db6-6df6807ae180.jpg)

**Comment by venits** [comment]
Hi,

looks like a problem with your dependencies. Uninstall **react-native-maps** and unlink them from project. (Also remove anything related to AIRMap from **Podfile**).

Reinstall and link modules again. It should fix the issue.

**Comment by jetonk** [comment]
@venits Thank you for the Uninstalling you were right, but now Markers do not show at all in the map.

**Comment by solace** [comment]
Experiencing the same issue. But zooming does not make the markers appear.

**Comment by donnes** [comment]
@venits This solution doest work for me.

react-native: 0.60.4
react-native-maps: 0.25.0
react-native-map-clustering: latest

**Comment by luisRubiera** [comment]
I had the same problem, i believe it was caused because i mixed `npm install` and `yarn install`. for those using `expo`, to correct the problem:
- `rm -Rf node_modules`
- `rm package-lock.json`
- `rm yarn-lock.json`
- `npm install`
- `expo install react-native-maps`
- `npm install react-native-map-clustering --save` ( you should already have done this earlier :p )

Done :heart: , now you can run it safely:
- `npm start`

**Comment by zelenko** [comment]
Experiencing the same issue:

-   "react": "16.8.3",
-   "react-dom": "^16.8.6",
-   "react-native": "https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz",
-   "react-native-map-clustering": "^2.0.2",
-   "react-native-maps": "~0.25.0",
