### ISSUE TITLE
Disable clusters at certain zoom level?

### ISSUE THREAD

**Issue by Werbelow** [venits/react-native-map-clustering#14]
Use case / issue:
When at least two map markers are in the same location, I can't zoom in far enough to split them up, it just keeps showing the cluster marker with the number 2 on it. 

I'm wondering if there is a way I could maybe disable the clustering at a certain zoom level, or somehow show both the markers below the cluster, when they are at the same location. 

Not entirely sure it's possible, but just wanted to check if it might be :)

**Comment by venits** [comment]
Case when both markers have exactly same location is rather unrealistic in real world. If you disable clustering you will still get one marker because they will cover each other.

In app, you can create one big marker and put more data to it.

It will be possible to create special cluster that will display two markers near each other, even though they have exactly same location.

**Comment by Werbelow** [comment]
Valid point, thanks :) In testing, we have gotten some exact locations, but you are right that in the real world, it would be less likely to have multiple markers in the exact location.

**Comment by strindhaug** [comment]
If the markers represent addresses it's not that unusual that several businesses share the same address, and if the coordinates are created from the street address they will have exactly the same coordinates.

**Comment by webstermobile** [comment]
first get the zoom level
second set the Marker 's prop cluster={false}
