### ISSUE TITLE
"zoom" in "calculateClustersForMap" function becomes NaN

### ISSUE THREAD

**Issue by soubhik-mondal-bitcanny** [venits/react-native-map-clustering#30]
I'm getting the following error, randomly:

`undefined is not an object (evaluating 'tree.range')`

I checked within the code and found that for some cases `getZoomLevel` function returns `zoom` as `NaN`.

The particular case which I tracked was this:

`bbox = [ 392.6867911219597, -28.446937064843333, -74.18819949030876, 148.92655940484119 ]`
`height = 592`
`width = 360`

In the meanwhile, I'm gonna try something like this: `zoom = this.getZoomLevel(bbox).zoom || 0;`

**Comment by venits** [comment]
Hi, in my module you cna find this code:
```javascript
if(this.state.region.longitudeDelta >= 40){
    zoom = 0;
} else {
    zoom = this.getZoomLevel(bbox).zoom;
}
```
This basically prevents this error. I don't really know why this is happening, it must be something wrong with 'geo-viewport' module I am using for calculating zoom.
If found that using above code is 100% fine and everything works as it should.

I don't really understand what you want to archive in calculating zoom level on your own.
Otherwise if you want do display zoom level to the user just use above code and it will work just fine.

**Comment by soubhik-mondal-bitcanny** [comment]
I'm not trying to calculate the zoom level on my own. Basically, the issue is that using your module *is* causing this error randomly, with no modification from my end... resulting in my app breaking.

**Comment by venits** [comment]
Hmm if will add this code to module to prevent returning NaN.
It is only happen when delta is large so we can assume that zoom will be equal to 0 in all cases.
```javascript
 if (isNaN( zoom.zoom )) {
      zoom.zoom = 0;
  }
```

**Comment by soubhik-mondal-bitcanny** [comment]
Yes, that should solve the issue.
