### ISSUE TITLE
2 or more markers with nearly the same coords stay always in the cluster

### ISSUE THREAD

**Issue by mafiusu** [venits/react-native-map-clustering#31]
Hello,

if I have two or more markers that are almost at the same coords. The markers are not displayed. Even if I zoom 100% the clusters stays active. How can I fix that?

**Comment by venits** [comment]
Hmm I don't know if you can really fix that because that how clustering works. When you have two markers at almost same coordinates they get clustered.
What you can do:
1. Send prop 'radius' with MapView that give you control of distance between markers before they get clustered. (In README.me you can find more information)
2. Change coordinates of one of the markers so they are not to close to each other.

**Comment by MaxFahr** [comment]
If it was possible to pass superclusters minZoom/maxZoom Options as props of the MapView, mafiusu could fix his issue properly.
