### ISSUE TITLE
I want to group markers by type

### ISSUE THREAD

**Issue by dbyilmaz** [venits/react-native-map-clustering#57]
I have two types
- Customers
- Users

I want to make different marker cluster per types. How do I? @venits  <br>
![1](https://user-images.githubusercontent.com/21238272/36024217-2230e3fa-0da0-11e8-92c3-e2c3ed62bdeb.png)

**Comment by Jacob-Allen** [comment]
I am interested in this as well. Did you ever solve getting different data sets to cluster independently from one another?

**Comment by blac3kman** [comment]
Same situation. Is there an example of using several clusters with different datasets.

**Comment by venits** [comment]
Hmm is this issue still relevant?

It could be handled by additional prop  **renderCluster** but it will require you to write whole cluster view from scratch.

On the other hand you will have full control over cluster logic.

Let me know if that is still needed.

**Comment by blac3kman** [comment]
@venits 
Hi. It was 6 months ago. If nobody didn't release it then, that situation is still alive.

**Comment by venits** [comment]
@blac3kman Hmm ok I will add this prop in free time and prepare some example code 💪

**Comment by blac3kman** [comment]
@venits Oh thanks man=)) It's great to read it!

**Comment by venits** [comment]
I added new prop called **renderCluster** that allows you to control logic and style of cluster.

Upgrade module to version **"3.0.3"**.

Here is code example of how it works:

```js
const renderCluster = cluster => {
  const { id, geometry, onPress, properties } = cluster;
  const points = properties.point_count;

  return (
    <Marker
      key={`cluster-${id}`}
      coordinate={{
        longitude: geometry.coordinates[0],
        latitude: geometry.coordinates[1]
      }}
      onPress={onPress}
    >
     <View>
       <Text>{points}</Text>
     </View>
   </Marker>
  );
};

return (
  <MapView
    renderCluster={renderCluster}
  >
    // markers
  </MapView>
);
```

I don't know it will fully solve this problem but at least it gives some control over clustering logic.

I don't want to add grouping clusters by type because it will take a lot of code and I want to maintain my codebase clear and easy.

I would personally recommend forking this repo and adding types on your own. It should be quite easy :) If any one has problems with setting it up, please contact me and we will figure something out together 💪

**Comment by thanhluantl2304** [comment]
That should not be closed. I want to group by markers's type. But the superCluster was automatically group any markers. renderCluster can not solve it. Please give me the solution!

**Comment by craig8two** [comment]
+1

**Comment by craig8two** [comment]
This would be an extremely useful feature.

**Comment by alexis-regnaud** [comment]
Is there any solution for that one ?
