### ISSUE TITLE
get markers in a cluster on Cluster Press

### ISSUE THREAD

**Issue by h4m3d66** [venits/react-native-map-clustering#74]
How can I get markers in a cluster on Cluster Press?

**Comment by venits** [comment]
There are two ways: 
1. use module version `<= 1.2.6`, and then in `onClusterPress` you will receive 2 parameters, one of them will be markers.
2. Implement it on your own. It's quite easy, because new version of module is like `150 lines of code`, so *5 minutes* to understand it and *5 minutes* to implement ;)

**Comment by h4m3d66** [comment]
Is there any special reason that it's not implemented in new version?

**Comment by venits** [comment]
Yes, I wanted to simplify the whole module, and make it more developers friendly, 
so anyone can implement only needed things.

*My goal is to create module that everyone can modify to own needs.*

**Comment by DikshaDeep** [comment]
Hello 

I want to de-cluster markers when i click on clusters so please tell me how to do this?

**Comment by salimakhtar92** [comment]
@DikshaDeep use module version ```1.2.6```
and write the following code
```
onClusterPress={ coordinates => console.log(coordinates) }
```
Then you will get ```lat```  and ```long```
